### ISSUE TITLE
⁨Not worki in ver.2.1.54

### ISSUE THREAD

**Issue by CuboidRasc** [cjdduarte/FreeWeekend#7]
This add-on cannot be installed into ver.2.1.54 at least.  Could you update this to adapt to the ver. ?

**Comment by cjdduarte** [comment]
> 

I will evaluate if I can separate the code. The problem is with V3.

**Comment by cjdduarte** [comment]
E esó funciona até o 2.1.35
![image](https://github.com/cjdduarte/Free_Weekend/assets/42243532/0f6c3823-ecd5-449a-baff-7273f936dcf1)
