### ISSUE TITLE
Doesn't run, even with V3 turned off

### ISSUE THREAD

**Issue by DocLukas** [cjdduarte/FreeWeekend#8]
I have a problem with it in Anki 2.1.60, I tried the Qt5 and Qt6 variant bot it doesn't work in any of these. My V3 scheduler is turned off in the settings. In the addons section it says it only runs with <= 2.1.35 

If there is anything else I can do to make it run please let me know, this addon was really amazing :,)

**Comment by RatHofCon001** [comment]
Being able to use with V3 would be amazing, please release an update!!

**Comment by cjdduarte** [comment]
Only 2.1.35

![image](https://github.com/cjdduarte/Free_Weekend/assets/42243532/6580a118-680b-4263-b1e9-aeef598600af)
