### ISSUE TITLE
Não funciona no ANKI ⁨2.1.58

### ISSUE THREAD

**Issue by carolinecpetillo** [cjdduarte/FreeWeekend#9]
Olá, não sei o motivo, mas a extensão não funciona no ANKI  ⁨2.1.58. V3 está desativado.
![image](https://github.com/cjdduarte/Free_Weekend/assets/115419016/a6fb350e-92b3-496c-ae0b-f6156d3039a3)

**Comment by cjdduarte** [comment]
Ele só funciona até o 2.1.35

![image](https://github.com/cjdduarte/Free_Weekend/assets/42243532/34b47e1f-ccd9-4be6-b1cf-c2d4a6ea8f7b)
